[package]
name = "rudu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4", features = ["derive"] }
walkdir = "2"
rayon = "1"
humansize = "2"
libc = "0.2"